version: '3.1'

services:
    client:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        container_name: Client
        command: sh -c 'npm run serve'
        ports:
            - 8081:8080
        networks:
            - frontend
networks:
    frontend:
