version: '3.1'

services:
    webserver:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        container_name: webserver
        ports:
            - "8081:80"